services:
  - type: web
    name: haps-backend
    env: python
    plan: free
    buildCommand: pip install -r requirement.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
